/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/schema.json
export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  favicon?: ImageWithAlt;
  bookNowLabel?: string;
  footerNote?: string;
  legalLinks?: Array<
    {
      _key: string;
    } & Link
  >;
  defaultSeo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: ImageWithAlt;
  noIndex?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
  externalUrl?: string;
};

export type Property = {
  _id: string;
  _type: "property";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: "seminyak" | "ubud";
  label?: string;
  logo?: ImageWithAlt;
  navItems?: Array<{
    label?: string;
    href?: string;
    inScope?: boolean;
    children?: Array<{
      label?: string;
      href?: string;
      inScope?: boolean;
      external?: boolean;
      _type: "navChild";
      _key: string;
    }>;
    _type: "navItem";
    _key: string;
  }>;
  addressLines?: Array<string>;
  phones?: Array<string>;
  email?: string;
  maps?: string;
  facebook?: string;
  instagram?: string;
  instagramApiUrl?: string;
  instagramFeedUrl?: string;
  bookingHref?: string;
  bookingWidgetId?: string;
  offersHref?: string;
  blogPosts?: Array<{
    title?: string;
    href?: string;
    _type: "blogTeaser";
    _key: string;
  }>;
  awardBadges?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  awardVariant?: "grid" | "marquee";
};

export type LegalPage = {
  _id: string;
  _type: "legalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  path?: "/terms-conditions" | "/privacy-policy";
  intro?: string;
  sections?: Array<
    | {
        heading?: string;
        text?: string;
        _type: "legalParagraph";
        _key: string;
      }
    | {
        heading?: string;
        items?: Array<string>;
        _type: "legalList";
        _key: string;
      }
  >;
  updatedAt?: string;
  seo?: Seo;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  author?: string;
  property?: "seminyak" | "ubud";
  order?: number;
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: string;
  group?: "retreat" | "wellness" | "culture";
  eyebrow?: string;
  paragraphs?: Array<string>;
  recommendedFor?: Array<string>;
  note?: string;
  sections?: Array<
    {
      _key: string;
    } & ExperienceSection
  >;
  blocks?: Array<
    {
      _key: string;
    } & BulletBlock
  >;
  programsHeading?: string;
  programs?: Array<
    {
      _key: string;
    } & ExperienceProgram
  >;
  inclusions?: Array<string>;
  price?: string;
  highlightsHeading?: string;
  highlights?: Array<
    {
      _key: string;
    } & ExperienceHighlight
  >;
  closingCta?: string;
  teamHeading?: string;
  team?: Array<
    {
      _key: string;
    } & TeamMember
  >;
  faqHeading?: string;
  faq?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  hero?: ImageWithAlt;
  gallery?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  seo?: Seo;
};

export type Room = {
  _id: string;
  _type: "room";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  property?: "seminyak" | "ubud";
  description?: string;
  details?: Array<
    {
      _key: string;
    } & DetailRow
  >;
  amenities?: Array<string>;
  facilities?: Array<string>;
  hero?: ImageWithAlt;
  gallery?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  order?: number;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  path?: string;
  property?: "seminyak" | "ubud";
  date?: string;
  order?: number;
  excerpt?: string;
  image?: ImageWithAlt;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  blocks?: Array<
    | ({
        _key: string;
      } & ArticleHeading)
    | ({
        _key: string;
      } & ArticleParagraph)
    | ({
        _key: string;
      } & ArticleList)
    | ({
        _key: string;
      } & ArticleImage)
    | ({
        _key: string;
      } & ArticlePoints)
    | ({
        _key: string;
      } & ArticlePrice)
    | ({
        _key: string;
      } & ArticleFaq)
  >;
  seo?: Seo;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  path?: string;
  property?: "seminyak" | "ubud";
  sections?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & SplitContentSection)
    | ({
        _key: string;
      } & GallerySection)
    | ({
        _key: string;
      } & AmenityGridSection)
    | ({
        _key: string;
      } & LinkCardGridSection)
    | ({
        _key: string;
      } & CollectionSection)
    | ({
        _key: string;
      } & PackageListSection)
    | ({
        _key: string;
      } & ProgramListSection)
    | ({
        _key: string;
      } & TreatmentListSection)
    | ({
        _key: string;
      } & BulletListSection)
    | ({
        _key: string;
      } & PriceTableSection)
    | ({
        _key: string;
      } & FaqSection)
    | ({
        _key: string;
      } & CtaSection)
    | ({
        _key: string;
      } & InquiryFormSection)
    | ({
        _key: string;
      } & AwardsSection)
    | ({
        _key: string;
      } & DealsSection)
    | ({
        _key: string;
      } & InstagramSection)
    | ({
        _key: string;
      } & BookingWidgetSection)
  >;
  seo?: Seo;
};

export type BookingWidgetSection = {
  _type: "bookingWidgetSection";
  heading?: string;
  widgetId?: string;
  anchor?: string;
  isHidden?: boolean;
};

export type InstagramSection = {
  _type: "instagramSection";
  heading?: string;
  feedUrl?: string;
  anchor?: string;
  isHidden?: boolean;
};

export type DealsSection = {
  _type: "dealsSection";
  bookingHref?: string;
  anchor?: string;
  isHidden?: boolean;
};

export type AwardsSection = {
  _type: "awardsSection";
  heading?: string;
  badges?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  variant?: "grid" | "marquee";
  anchor?: string;
  isHidden?: boolean;
};

export type InquiryFormSection = {
  _type: "inquiryFormSection";
  heading?: string;
  fields?: Array<{
    kind?:
      | "text"
      | "email"
      | "tel"
      | "number"
      | "date"
      | "textarea"
      | "radio"
      | "checkbox";
    label?: string;
    name?: string;
    options?: Array<string>;
    required?: boolean;
    _type: "inquiryField";
    _key: string;
  }>;
  submitLabel?: string;
  confirmation?: string;
  tone?: "sand" | "sand-deep";
  anchor?: string;
  isHidden?: boolean;
};

export type CtaSection = {
  _type: "ctaSection";
  eyebrow?: string;
  heading?: string;
  body?: string;
  actions?: Array<
    {
      _key: string;
    } & Link
  >;
  image?: ImageWithAlt;
  tone?: "sand" | "sand-deep";
  anchor?: string;
  isHidden?: boolean;
};

export type FaqSection = {
  _type: "faqSection";
  heading?: string;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  tone?: "sand" | "sand-deep";
  anchor?: string;
  isHidden?: boolean;
};

export type PriceTableSection = {
  _type: "priceTableSection";
  heading?: string;
  table?: PriceTable;
  tone?: "sand" | "sand-deep";
  anchor?: string;
  isHidden?: boolean;
};

export type PriceTable = {
  _type: "priceTable";
  columns?: Array<string>;
  rows?: Array<
    {
      _key: string;
    } & PriceRow
  >;
};

export type BulletListSection = {
  _type: "bulletListSection";
  eyebrow?: string;
  heading?: string;
  intro?: string;
  groups?: Array<
    {
      _key: string;
    } & BulletGroup
  >;
  tone?: "sand" | "sand-deep";
  anchor?: string;
  isHidden?: boolean;
};

export type TreatmentListSection = {
  _type: "treatmentListSection";
  eyebrow?: string;
  heading?: string;
  intro?: string;
  notes?: Array<string>;
  categories?: Array<
    {
      _key: string;
    } & TreatmentCategory
  >;
  cta?: Link;
  tone?: "sand" | "sand-deep";
  anchor?: string;
  isHidden?: boolean;
};

export type Link = {
  _type: "link";
  label?: string;
  href?: string;
  external?: boolean;
  inScope?: boolean;
  variant?: "solid" | "outline";
};

export type ProgramListSection = {
  _type: "programListSection";
  heading?: string;
  tiers?: Array<
    {
      _key: string;
    } & ExperienceProgram
  >;
  tone?: "sand" | "sand-deep";
  anchor?: string;
  isHidden?: boolean;
};

export type PackageSetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "packageSet";
};

export type PackageListSection = {
  _type: "packageListSection";
  eyebrow?: string;
  heading?: string;
  intro?: string;
  source?: "inline" | "reference";
  packages?: Array<
    {
      _key: string;
    } & PackageItem
  >;
  packageSet?: PackageSetReference;
  tone?: "sand" | "sand-deep";
  anchor?: string;
  isHidden?: boolean;
};

export type PackageSet = {
  _id: string;
  _type: "packageSet";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  property?: "seminyak" | "ubud";
  alwaysIncluded?: Array<string>;
  packages?: Array<
    {
      _key: string;
    } & PackageItem
  >;
};

export type CollectionSection = {
  _type: "collectionSection";
  eyebrow?: string;
  heading?: string;
  intro?: string;
  collection?: "room" | "post" | "experience" | "testimonial";
  property?: "" | "seminyak" | "ubud";
  group?: "" | "retreat" | "wellness" | "culture";
  limit?: number;
  action?: Link;
  tone?: "sand" | "sand-deep";
  anchor?: string;
  isHidden?: boolean;
};

export type LinkCardGridSection = {
  _type: "linkCardGridSection";
  eyebrow?: string;
  heading?: string;
  items?: Array<{
    label?: string;
    href?: string;
    image?: ImageWithAlt;
    inScope?: boolean;
    _type: "linkCard";
    _key: string;
  }>;
  columns?: 2 | 3 | 4;
  tone?: "sand" | "sand-deep";
  anchor?: string;
  isHidden?: boolean;
};

export type AmenityGridSection = {
  _type: "amenityGridSection";
  heading?: string;
  amenities?: Array<
    {
      _key: string;
    } & Amenity
  >;
  tone?: "sand" | "sand-deep";
  anchor?: string;
  isHidden?: boolean;
};

export type GallerySection = {
  _type: "gallerySection";
  eyebrow?: string;
  heading?: string;
  images?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  alt?: string;
  tone?: "sand" | "sand-deep";
  anchor?: string;
  isHidden?: boolean;
};

export type SplitContentSection = {
  _type: "splitContentSection";
  eyebrow?: string;
  heading?: string;
  paragraphs?: Array<string>;
  script?: string;
  image?: ImageWithAlt;
  imageSide?: "right" | "left";
  action?: Link;
  tone?: "sand" | "sand-deep";
  anchor?: string;
  isHidden?: boolean;
};

export type RichTextSection = {
  _type: "richTextSection";
  eyebrow?: string;
  heading?: string;
  body?: PortableText;
  tone?: "sand" | "sand-deep";
  anchor?: string;
  isHidden?: boolean;
};

export type PortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        blank?: boolean;
        _type: "textLink";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & ImageWithAlt)
>;

export type HeroSection = {
  _type: "heroSection";
  images?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  eyebrow?: string;
  title?: string;
  alt?: string;
  anchor?: string;
  isHidden?: boolean;
};

export type ArticlePrice = {
  _type: "articlePrice";
  table?: PriceTable;
};

export type ArticleFaq = {
  _type: "articleFaq";
  heading?: string;
  items?: Array<
    {
      _key: string;
    } & FaqItem
  >;
};

export type ArticlePoints = {
  _type: "articlePoints";
  ordered?: boolean;
  items?: Array<
    {
      _key: string;
    } & ArticlePointItem
  >;
};

export type ArticlePointItem = {
  _type: "articlePointItem";
  label?: string;
  body?: Array<
    | ({
        _key: string;
      } & ArticleParagraph)
    | ({
        _key: string;
      } & ArticleImage)
  >;
};

export type ArticleImage = {
  _type: "articleImage";
  image?: ImageWithAlt;
};

export type ArticleList = {
  _type: "articleList";
  items?: Array<string>;
};

export type ArticleParagraph = {
  _type: "articleParagraph";
  text?: string;
};

export type ArticleHeading = {
  _type: "articleHeading";
  text?: string;
};

export type BulletBlock = {
  _type: "bulletBlock";
  heading?: string;
  intro?: string;
  groups?: Array<
    {
      _key: string;
    } & BulletGroup
  >;
};

export type TeamMember = {
  _type: "teamMember";
  name?: string;
  photo?: ImageWithAlt;
  bio?: string;
};

export type ExperienceProgram = {
  _type: "experienceProgram";
  name?: string;
  groups?: Array<
    {
      _key: string;
    } & BulletGroup
  >;
};

export type ExperienceHighlight = {
  _type: "experienceHighlight";
  icon?: ImageWithAlt;
  title?: string;
  body?: string;
};

export type ExperienceSection = {
  _type: "experienceSection";
  heading?: string;
  body?: Array<string>;
  image?: ImageWithAlt;
};

export type TreatmentCategory = {
  _type: "treatmentCategory";
  name?: string;
  image?: ImageWithAlt;
  treatments?: Array<
    {
      _key: string;
    } & TreatmentItem
  >;
};

export type TreatmentItem = {
  _type: "treatmentItem";
  name?: string;
  description?: string;
  options?: Array<
    {
      _key: string;
    } & TreatmentOption
  >;
  includes?: Array<string>;
};

export type TreatmentOption = {
  _type: "treatmentOption";
  label?: string;
  href?: string;
};

export type PackageItem = {
  _type: "packageItem";
  name?: string;
  images?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  description?: string;
  meta?: Array<
    {
      _key: string;
    } & PackageMeta
  >;
  benefitsHeading?: string;
  benefits?: Array<string>;
  notes?: Array<string>;
  ctas?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type PackageMeta = {
  _type: "packageMeta";
  label?: string;
  value?: string;
};

export type PriceRow = {
  _type: "priceRow";
  cells?: Array<string>;
};

export type Amenity = {
  _type: "amenity";
  icon?:
    | "wifi"
    | "spa"
    | "dining"
    | "romance"
    | "service"
    | "yoga"
    | "gym"
    | "class";
  title?: string;
  subtitle?: string;
};

export type DetailRow = {
  _type: "detailRow";
  label?: string;
  value?: string;
};

export type BulletGroup = {
  _type: "bulletGroup";
  heading?: string;
  items?: Array<string>;
};

export type FaqItem = {
  _type: "faqItem";
  question?: string;
  answer?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SiteSettings
  | Seo
  | SanityImageAssetReference
  | ImageWithAlt
  | Property
  | LegalPage
  | Testimonial
  | Experience
  | Room
  | Slug
  | Category
  | CategoryReference
  | Post
  | Page
  | BookingWidgetSection
  | InstagramSection
  | DealsSection
  | AwardsSection
  | InquiryFormSection
  | CtaSection
  | FaqSection
  | PriceTableSection
  | PriceTable
  | BulletListSection
  | TreatmentListSection
  | Link
  | ProgramListSection
  | PackageSetReference
  | PackageListSection
  | PackageSet
  | CollectionSection
  | LinkCardGridSection
  | AmenityGridSection
  | GallerySection
  | SplitContentSection
  | RichTextSection
  | PortableText
  | HeroSection
  | ArticlePrice
  | ArticleFaq
  | ArticlePoints
  | ArticlePointItem
  | ArticleImage
  | ArticleList
  | ArticleParagraph
  | ArticleHeading
  | BulletBlock
  | TeamMember
  | ExperienceProgram
  | ExperienceHighlight
  | ExperienceSection
  | TreatmentCategory
  | TreatmentItem
  | TreatmentOption
  | PackageItem
  | PackageMeta
  | PriceRow
  | Amenity
  | DetailRow
  | BulletGroup
  | FaqItem
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: pageByPathQuery
// Query: *[_type == "page" && path == $path][0]{    _id,    _type,    title,    path,    property,    seo {  title,  description,  image {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot},  noIndex},    sections[] {  ...,  image {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot},  images[] {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot},  badges[] {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot},  items[]{    ...,    image {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot}  },  packages[]{    ...,    images[] {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot}  },  categories[]{    ...,    image {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot}  },  packageSet->{    _id,    title,    alwaysIncluded,    packages[]{      ...,      images[] {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot}    }  }}  }
export type PageByPathQueryResult = {
  _id: string;
  _type: "page";
  title: string | null;
  path: string | null;
  property: "seminyak" | "ubud" | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _type: "imageWithAlt";
      asset: SanityImageAssetReference | null;
      alt: string | null;
      caption: string | null;
      externalUrl: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
    noIndex: boolean | null;
  } | null;
  sections: Array<
    | {
        _key: string;
        _type: "amenityGridSection";
        heading?: string;
        amenities?: Array<
          {
            _key: string;
          } & Amenity
        >;
        tone?: "sand-deep" | "sand";
        anchor?: string;
        isHidden?: boolean;
        image: null;
        images: null;
        badges: null;
        items: null;
        packages: null;
        categories: null;
        packageSet: null;
      }
    | {
        _key: string;
        _type: "awardsSection";
        heading?: string;
        badges: Array<{
          _type: "imageWithAlt";
          asset: SanityImageAssetReference | null;
          alt: string | null;
          caption: string | null;
          externalUrl: string | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
        }> | null;
        variant?: "grid" | "marquee";
        anchor?: string;
        isHidden?: boolean;
        image: null;
        images: null;
        items: null;
        packages: null;
        categories: null;
        packageSet: null;
      }
    | {
        _key: string;
        _type: "bookingWidgetSection";
        heading?: string;
        widgetId?: string;
        anchor?: string;
        isHidden?: boolean;
        image: null;
        images: null;
        badges: null;
        items: null;
        packages: null;
        categories: null;
        packageSet: null;
      }
    | {
        _key: string;
        _type: "bulletListSection";
        eyebrow?: string;
        heading?: string;
        intro?: string;
        groups?: Array<
          {
            _key: string;
          } & BulletGroup
        >;
        tone?: "sand-deep" | "sand";
        anchor?: string;
        isHidden?: boolean;
        image: null;
        images: null;
        badges: null;
        items: null;
        packages: null;
        categories: null;
        packageSet: null;
      }
    | {
        _key: string;
        _type: "collectionSection";
        eyebrow?: string;
        heading?: string;
        intro?: string;
        collection?: "experience" | "post" | "room" | "testimonial";
        property?: "" | "seminyak" | "ubud";
        group?: "" | "culture" | "retreat" | "wellness";
        limit?: number;
        action?: Link;
        tone?: "sand-deep" | "sand";
        anchor?: string;
        isHidden?: boolean;
        image: null;
        images: null;
        badges: null;
        items: null;
        packages: null;
        categories: null;
        packageSet: null;
      }
    | {
        _key: string;
        _type: "ctaSection";
        eyebrow?: string;
        heading?: string;
        body?: string;
        actions?: Array<
          {
            _key: string;
          } & Link
        >;
        image: {
          _type: "imageWithAlt";
          asset: SanityImageAssetReference | null;
          alt: string | null;
          caption: string | null;
          externalUrl: string | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
        } | null;
        tone?: "sand-deep" | "sand";
        anchor?: string;
        isHidden?: boolean;
        images: null;
        badges: null;
        items: null;
        packages: null;
        categories: null;
        packageSet: null;
      }
    | {
        _key: string;
        _type: "dealsSection";
        bookingHref?: string;
        anchor?: string;
        isHidden?: boolean;
        image: null;
        images: null;
        badges: null;
        items: null;
        packages: null;
        categories: null;
        packageSet: null;
      }
    | {
        _key: string;
        _type: "faqSection";
        heading?: string;
        faqs?: Array<
          {
            _key: string;
          } & FaqItem
        >;
        tone?: "sand-deep" | "sand";
        anchor?: string;
        isHidden?: boolean;
        image: null;
        images: null;
        badges: null;
        items: null;
        packages: null;
        categories: null;
        packageSet: null;
      }
    | {
        _key: string;
        _type: "gallerySection";
        eyebrow?: string;
        heading?: string;
        images: Array<{
          _type: "imageWithAlt";
          asset: SanityImageAssetReference | null;
          alt: string | null;
          caption: string | null;
          externalUrl: string | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
        }> | null;
        alt?: string;
        tone?: "sand-deep" | "sand";
        anchor?: string;
        isHidden?: boolean;
        image: null;
        badges: null;
        items: null;
        packages: null;
        categories: null;
        packageSet: null;
      }
    | {
        _key: string;
        _type: "heroSection";
        images: Array<{
          _type: "imageWithAlt";
          asset: SanityImageAssetReference | null;
          alt: string | null;
          caption: string | null;
          externalUrl: string | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
        }> | null;
        eyebrow?: string;
        title?: string;
        alt?: string;
        anchor?: string;
        isHidden?: boolean;
        image: null;
        badges: null;
        items: null;
        packages: null;
        categories: null;
        packageSet: null;
      }
    | {
        _key: string;
        _type: "inquiryFormSection";
        heading?: string;
        fields?: Array<{
          kind?:
            | "checkbox"
            | "date"
            | "email"
            | "number"
            | "radio"
            | "tel"
            | "text"
            | "textarea";
          label?: string;
          name?: string;
          options?: Array<string>;
          required?: boolean;
          _type: "inquiryField";
          _key: string;
        }>;
        submitLabel?: string;
        confirmation?: string;
        tone?: "sand-deep" | "sand";
        anchor?: string;
        isHidden?: boolean;
        image: null;
        images: null;
        badges: null;
        items: null;
        packages: null;
        categories: null;
        packageSet: null;
      }
    | {
        _key: string;
        _type: "instagramSection";
        heading?: string;
        feedUrl?: string;
        anchor?: string;
        isHidden?: boolean;
        image: null;
        images: null;
        badges: null;
        items: null;
        packages: null;
        categories: null;
        packageSet: null;
      }
    | {
        _key: string;
        _type: "linkCardGridSection";
        eyebrow?: string;
        heading?: string;
        items: Array<{
          label?: string;
          href?: string;
          image: {
            _type: "imageWithAlt";
            asset: SanityImageAssetReference | null;
            alt: string | null;
            caption: string | null;
            externalUrl: string | null;
            crop: SanityImageCrop | null;
            hotspot: SanityImageHotspot | null;
          } | null;
          inScope?: boolean;
          _type: "linkCard";
          _key: string;
        }> | null;
        columns?: 2 | 3 | 4;
        tone?: "sand-deep" | "sand";
        anchor?: string;
        isHidden?: boolean;
        image: null;
        images: null;
        badges: null;
        packages: null;
        categories: null;
        packageSet: null;
      }
    | {
        _key: string;
        _type: "packageListSection";
        eyebrow?: string;
        heading?: string;
        intro?: string;
        source?: "inline" | "reference";
        packages: Array<{
          _key: string;
          _type: "packageItem";
          name?: string;
          images: Array<{
            _type: "imageWithAlt";
            asset: SanityImageAssetReference | null;
            alt: string | null;
            caption: string | null;
            externalUrl: string | null;
            crop: SanityImageCrop | null;
            hotspot: SanityImageHotspot | null;
          }> | null;
          description?: string;
          meta?: Array<
            {
              _key: string;
            } & PackageMeta
          >;
          benefitsHeading?: string;
          benefits?: Array<string>;
          notes?: Array<string>;
          ctas?: Array<
            {
              _key: string;
            } & Link
          >;
        }> | null;
        packageSet: {
          _id: string;
          title: string | null;
          alwaysIncluded: Array<string> | null;
          packages: Array<{
            _key: string;
            _type: "packageItem";
            name?: string;
            images: Array<{
              _type: "imageWithAlt";
              asset: SanityImageAssetReference | null;
              alt: string | null;
              caption: string | null;
              externalUrl: string | null;
              crop: SanityImageCrop | null;
              hotspot: SanityImageHotspot | null;
            }> | null;
            description?: string;
            meta?: Array<
              {
                _key: string;
              } & PackageMeta
            >;
            benefitsHeading?: string;
            benefits?: Array<string>;
            notes?: Array<string>;
            ctas?: Array<
              {
                _key: string;
              } & Link
            >;
          }> | null;
        } | null;
        tone?: "sand-deep" | "sand";
        anchor?: string;
        isHidden?: boolean;
        image: null;
        images: null;
        badges: null;
        items: null;
        categories: null;
      }
    | {
        _key: string;
        _type: "priceTableSection";
        heading?: string;
        table?: PriceTable;
        tone?: "sand-deep" | "sand";
        anchor?: string;
        isHidden?: boolean;
        image: null;
        images: null;
        badges: null;
        items: null;
        packages: null;
        categories: null;
        packageSet: null;
      }
    | {
        _key: string;
        _type: "programListSection";
        heading?: string;
        tiers?: Array<
          {
            _key: string;
          } & ExperienceProgram
        >;
        tone?: "sand-deep" | "sand";
        anchor?: string;
        isHidden?: boolean;
        image: null;
        images: null;
        badges: null;
        items: null;
        packages: null;
        categories: null;
        packageSet: null;
      }
    | {
        _key: string;
        _type: "richTextSection";
        eyebrow?: string;
        heading?: string;
        body?: PortableText;
        tone?: "sand-deep" | "sand";
        anchor?: string;
        isHidden?: boolean;
        image: null;
        images: null;
        badges: null;
        items: null;
        packages: null;
        categories: null;
        packageSet: null;
      }
    | {
        _key: string;
        _type: "splitContentSection";
        eyebrow?: string;
        heading?: string;
        paragraphs?: Array<string>;
        script?: string;
        image: {
          _type: "imageWithAlt";
          asset: SanityImageAssetReference | null;
          alt: string | null;
          caption: string | null;
          externalUrl: string | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
        } | null;
        imageSide?: "left" | "right";
        action?: Link;
        tone?: "sand-deep" | "sand";
        anchor?: string;
        isHidden?: boolean;
        images: null;
        badges: null;
        items: null;
        packages: null;
        categories: null;
        packageSet: null;
      }
    | {
        _key: string;
        _type: "treatmentListSection";
        eyebrow?: string;
        heading?: string;
        intro?: string;
        notes?: Array<string>;
        categories: Array<{
          _key: string;
          _type: "treatmentCategory";
          name?: string;
          image: {
            _type: "imageWithAlt";
            asset: SanityImageAssetReference | null;
            alt: string | null;
            caption: string | null;
            externalUrl: string | null;
            crop: SanityImageCrop | null;
            hotspot: SanityImageHotspot | null;
          } | null;
          treatments?: Array<
            {
              _key: string;
            } & TreatmentItem
          >;
        }> | null;
        cta?: Link;
        tone?: "sand-deep" | "sand";
        anchor?: string;
        isHidden?: boolean;
        image: null;
        images: null;
        badges: null;
        items: null;
        packages: null;
        packageSet: null;
      }
  > | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: allPagePathsQuery
// Query: *[_type == "page" && defined(path)].path
export type AllPagePathsQueryResult = Array<string>;

// Source: src/sanity/lib/queries.ts
// Variable: postByPathQuery
// Query: *[_type == "post" && path == $path][0] {  _id,  _type,  title,  path,  property,  date,  order,  excerpt,  image {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot},  "categories": categories[]->{_id, title, "slug": slug.current},  blocks[] {  ...,  _type == "articleImage" => {    image {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot}  },  _type == "articlePoints" => {    items[]{      ...,      body[]{        ...,        image {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot}      }    }  }},  seo {  title,  description,  image {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot},  noIndex}}
export type PostByPathQueryResult = {
  _id: string;
  _type: "post";
  title: string | null;
  path: string | null;
  property: "seminyak" | "ubud" | null;
  date: string | null;
  order: number | null;
  excerpt: string | null;
  image: {
    _type: "imageWithAlt";
    asset: SanityImageAssetReference | null;
    alt: string | null;
    caption: string | null;
    externalUrl: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  blocks: Array<
    | {
        _key: string;
        _type: "articleFaq";
        heading?: string;
        items?: Array<
          {
            _key: string;
          } & FaqItem
        >;
      }
    | {
        _key: string;
        _type: "articleHeading";
        text?: string;
      }
    | {
        _key: string;
        _type: "articleImage";
        image: {
          _type: "imageWithAlt";
          asset: SanityImageAssetReference | null;
          alt: string | null;
          caption: string | null;
          externalUrl: string | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
        } | null;
      }
    | {
        _key: string;
        _type: "articleList";
        items?: Array<string>;
      }
    | {
        _key: string;
        _type: "articleParagraph";
        text?: string;
      }
    | {
        _key: string;
        _type: "articlePoints";
        ordered?: boolean;
        items: Array<{
          _key: string;
          _type: "articlePointItem";
          label?: string;
          body: Array<
            | {
                _key: string;
                _type: "articleImage";
                image: {
                  _type: "imageWithAlt";
                  asset: SanityImageAssetReference | null;
                  alt: string | null;
                  caption: string | null;
                  externalUrl: string | null;
                  crop: SanityImageCrop | null;
                  hotspot: SanityImageHotspot | null;
                } | null;
              }
            | {
                _key: string;
                _type: "articleParagraph";
                text?: string;
                image: null;
              }
          > | null;
        }> | null;
      }
    | {
        _key: string;
        _type: "articlePrice";
        table?: PriceTable;
      }
  > | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _type: "imageWithAlt";
      asset: SanityImageAssetReference | null;
      alt: string | null;
      caption: string | null;
      externalUrl: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
    noIndex: boolean | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: allPostsQuery
// Query: *[_type == "post" && defined(path)] | order(date desc, order asc) {  _id,  _type,  title,  path,  property,  date,  order,  excerpt,  image {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot},  "categories": categories[]->{_id, title, "slug": slug.current},  blocks[] {  ...,  _type == "articleImage" => {    image {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot}  },  _type == "articlePoints" => {    items[]{      ...,      body[]{        ...,        image {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot}      }    }  }},  seo {  title,  description,  image {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot},  noIndex}}
export type AllPostsQueryResult = Array<{
  _id: string;
  _type: "post";
  title: string | null;
  path: string;
  property: "seminyak" | "ubud" | null;
  date: string | null;
  order: number | null;
  excerpt: string | null;
  image: {
    _type: "imageWithAlt";
    asset: SanityImageAssetReference | null;
    alt: string | null;
    caption: string | null;
    externalUrl: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  blocks: Array<
    | {
        _key: string;
        _type: "articleFaq";
        heading?: string;
        items?: Array<
          {
            _key: string;
          } & FaqItem
        >;
      }
    | {
        _key: string;
        _type: "articleHeading";
        text?: string;
      }
    | {
        _key: string;
        _type: "articleImage";
        image: {
          _type: "imageWithAlt";
          asset: SanityImageAssetReference | null;
          alt: string | null;
          caption: string | null;
          externalUrl: string | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
        } | null;
      }
    | {
        _key: string;
        _type: "articleList";
        items?: Array<string>;
      }
    | {
        _key: string;
        _type: "articleParagraph";
        text?: string;
      }
    | {
        _key: string;
        _type: "articlePoints";
        ordered?: boolean;
        items: Array<{
          _key: string;
          _type: "articlePointItem";
          label?: string;
          body: Array<
            | {
                _key: string;
                _type: "articleImage";
                image: {
                  _type: "imageWithAlt";
                  asset: SanityImageAssetReference | null;
                  alt: string | null;
                  caption: string | null;
                  externalUrl: string | null;
                  crop: SanityImageCrop | null;
                  hotspot: SanityImageHotspot | null;
                } | null;
              }
            | {
                _key: string;
                _type: "articleParagraph";
                text?: string;
                image: null;
              }
          > | null;
        }> | null;
      }
    | {
        _key: string;
        _type: "articlePrice";
        table?: PriceTable;
      }
  > | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _type: "imageWithAlt";
      asset: SanityImageAssetReference | null;
      alt: string | null;
      caption: string | null;
      externalUrl: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
    noIndex: boolean | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: postsByPropertyQuery
// Query: *[_type == "post" && property == $property && defined(path)] | order(date desc, order asc) {  _id,  _type,  title,  path,  property,  date,  order,  excerpt,  image {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot},  "categories": categories[]->{_id, title, "slug": slug.current},  blocks[] {  ...,  _type == "articleImage" => {    image {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot}  },  _type == "articlePoints" => {    items[]{      ...,      body[]{        ...,        image {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot}      }    }  }},  seo {  title,  description,  image {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot},  noIndex}}
export type PostsByPropertyQueryResult = Array<{
  _id: string;
  _type: "post";
  title: string | null;
  path: string | null;
  property: "seminyak" | "ubud" | null;
  date: string | null;
  order: number | null;
  excerpt: string | null;
  image: {
    _type: "imageWithAlt";
    asset: SanityImageAssetReference | null;
    alt: string | null;
    caption: string | null;
    externalUrl: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  blocks: Array<
    | {
        _key: string;
        _type: "articleFaq";
        heading?: string;
        items?: Array<
          {
            _key: string;
          } & FaqItem
        >;
      }
    | {
        _key: string;
        _type: "articleHeading";
        text?: string;
      }
    | {
        _key: string;
        _type: "articleImage";
        image: {
          _type: "imageWithAlt";
          asset: SanityImageAssetReference | null;
          alt: string | null;
          caption: string | null;
          externalUrl: string | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
        } | null;
      }
    | {
        _key: string;
        _type: "articleList";
        items?: Array<string>;
      }
    | {
        _key: string;
        _type: "articleParagraph";
        text?: string;
      }
    | {
        _key: string;
        _type: "articlePoints";
        ordered?: boolean;
        items: Array<{
          _key: string;
          _type: "articlePointItem";
          label?: string;
          body: Array<
            | {
                _key: string;
                _type: "articleImage";
                image: {
                  _type: "imageWithAlt";
                  asset: SanityImageAssetReference | null;
                  alt: string | null;
                  caption: string | null;
                  externalUrl: string | null;
                  crop: SanityImageCrop | null;
                  hotspot: SanityImageHotspot | null;
                } | null;
              }
            | {
                _key: string;
                _type: "articleParagraph";
                text?: string;
                image: null;
              }
          > | null;
        }> | null;
      }
    | {
        _key: string;
        _type: "articlePrice";
        table?: PriceTable;
      }
  > | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _type: "imageWithAlt";
      asset: SanityImageAssetReference | null;
      alt: string | null;
      caption: string | null;
      externalUrl: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
    noIndex: boolean | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: allPostPathsQuery
// Query: *[_type == "post" && defined(path)].path
export type AllPostPathsQueryResult = Array<string>;

// Source: src/sanity/lib/queries.ts
// Variable: allRoomsQuery
// Query: *[_type == "room" && defined(slug.current)] | order(property asc, order asc, title asc) {  _id,  _type,  title,  "slug": slug.current,  property,  description,  details,  amenities,  facilities,  hero {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot},  gallery[] {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot},  order,  seo {  title,  description,  image {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot},  noIndex}}
export type AllRoomsQueryResult = Array<{
  _id: string;
  _type: "room";
  title: string | null;
  slug: string | null;
  property: "seminyak" | "ubud" | null;
  description: string | null;
  details: Array<
    {
      _key: string;
    } & DetailRow
  > | null;
  amenities: Array<string> | null;
  facilities: Array<string> | null;
  hero: {
    _type: "imageWithAlt";
    asset: SanityImageAssetReference | null;
    alt: string | null;
    caption: string | null;
    externalUrl: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  gallery: Array<{
    _type: "imageWithAlt";
    asset: SanityImageAssetReference | null;
    alt: string | null;
    caption: string | null;
    externalUrl: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  order: number | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _type: "imageWithAlt";
      asset: SanityImageAssetReference | null;
      alt: string | null;
      caption: string | null;
      externalUrl: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
    noIndex: boolean | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: roomsByPropertyQuery
// Query: *[_type == "room" && property == $property && defined(slug.current)] | order(order asc, title asc) {  _id,  _type,  title,  "slug": slug.current,  property,  description,  details,  amenities,  facilities,  hero {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot},  gallery[] {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot},  order,  seo {  title,  description,  image {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot},  noIndex}}
export type RoomsByPropertyQueryResult = Array<{
  _id: string;
  _type: "room";
  title: string | null;
  slug: string | null;
  property: "seminyak" | "ubud" | null;
  description: string | null;
  details: Array<
    {
      _key: string;
    } & DetailRow
  > | null;
  amenities: Array<string> | null;
  facilities: Array<string> | null;
  hero: {
    _type: "imageWithAlt";
    asset: SanityImageAssetReference | null;
    alt: string | null;
    caption: string | null;
    externalUrl: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  gallery: Array<{
    _type: "imageWithAlt";
    asset: SanityImageAssetReference | null;
    alt: string | null;
    caption: string | null;
    externalUrl: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  order: number | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _type: "imageWithAlt";
      asset: SanityImageAssetReference | null;
      alt: string | null;
      caption: string | null;
      externalUrl: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
    noIndex: boolean | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: allExperiencesQuery
// Query: *[_type == "experience" && defined(slug)] | order(group asc, title asc) {  _id,  _type,  title,  slug,  group,  eyebrow,  paragraphs,  recommendedFor,  note,  sections[]{    ...,    image {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot}  },  blocks,  programsHeading,  programs,  inclusions,  price,  highlightsHeading,  highlights[]{    ...,    icon {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot}  },  closingCta,  teamHeading,  team[]{    ...,    photo {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot}  },  faqHeading,  faq,  hero {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot},  gallery[] {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot},  seo {  title,  description,  image {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot},  noIndex}}
export type AllExperiencesQueryResult = Array<{
  _id: string;
  _type: "experience";
  title: string | null;
  slug: string;
  group: "culture" | "retreat" | "wellness" | null;
  eyebrow: string | null;
  paragraphs: Array<string> | null;
  recommendedFor: Array<string> | null;
  note: string | null;
  sections: Array<{
    _key: string;
    _type: "experienceSection";
    heading?: string;
    body?: Array<string>;
    image: {
      _type: "imageWithAlt";
      asset: SanityImageAssetReference | null;
      alt: string | null;
      caption: string | null;
      externalUrl: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
  }> | null;
  blocks: Array<
    {
      _key: string;
    } & BulletBlock
  > | null;
  programsHeading: string | null;
  programs: Array<
    {
      _key: string;
    } & ExperienceProgram
  > | null;
  inclusions: Array<string> | null;
  price: string | null;
  highlightsHeading: string | null;
  highlights: Array<{
    _key: string;
    _type: "experienceHighlight";
    icon: {
      _type: "imageWithAlt";
      asset: SanityImageAssetReference | null;
      alt: string | null;
      caption: string | null;
      externalUrl: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
    title?: string;
    body?: string;
  }> | null;
  closingCta: string | null;
  teamHeading: string | null;
  team: Array<{
    _key: string;
    _type: "teamMember";
    name?: string;
    photo: {
      _type: "imageWithAlt";
      asset: SanityImageAssetReference | null;
      alt: string | null;
      caption: string | null;
      externalUrl: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
    bio?: string;
  }> | null;
  faqHeading: string | null;
  faq: Array<
    {
      _key: string;
    } & FaqItem
  > | null;
  hero: {
    _type: "imageWithAlt";
    asset: SanityImageAssetReference | null;
    alt: string | null;
    caption: string | null;
    externalUrl: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  gallery: Array<{
    _type: "imageWithAlt";
    asset: SanityImageAssetReference | null;
    alt: string | null;
    caption: string | null;
    externalUrl: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _type: "imageWithAlt";
      asset: SanityImageAssetReference | null;
      alt: string | null;
      caption: string | null;
      externalUrl: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
    noIndex: boolean | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: experienceBySlugQuery
// Query: *[_type == "experience" && slug == $slug][0] {  _id,  _type,  title,  slug,  group,  eyebrow,  paragraphs,  recommendedFor,  note,  sections[]{    ...,    image {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot}  },  blocks,  programsHeading,  programs,  inclusions,  price,  highlightsHeading,  highlights[]{    ...,    icon {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot}  },  closingCta,  teamHeading,  team[]{    ...,    photo {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot}  },  faqHeading,  faq,  hero {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot},  gallery[] {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot},  seo {  title,  description,  image {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot},  noIndex}}
export type ExperienceBySlugQueryResult = {
  _id: string;
  _type: "experience";
  title: string | null;
  slug: string | null;
  group: "culture" | "retreat" | "wellness" | null;
  eyebrow: string | null;
  paragraphs: Array<string> | null;
  recommendedFor: Array<string> | null;
  note: string | null;
  sections: Array<{
    _key: string;
    _type: "experienceSection";
    heading?: string;
    body?: Array<string>;
    image: {
      _type: "imageWithAlt";
      asset: SanityImageAssetReference | null;
      alt: string | null;
      caption: string | null;
      externalUrl: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
  }> | null;
  blocks: Array<
    {
      _key: string;
    } & BulletBlock
  > | null;
  programsHeading: string | null;
  programs: Array<
    {
      _key: string;
    } & ExperienceProgram
  > | null;
  inclusions: Array<string> | null;
  price: string | null;
  highlightsHeading: string | null;
  highlights: Array<{
    _key: string;
    _type: "experienceHighlight";
    icon: {
      _type: "imageWithAlt";
      asset: SanityImageAssetReference | null;
      alt: string | null;
      caption: string | null;
      externalUrl: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
    title?: string;
    body?: string;
  }> | null;
  closingCta: string | null;
  teamHeading: string | null;
  team: Array<{
    _key: string;
    _type: "teamMember";
    name?: string;
    photo: {
      _type: "imageWithAlt";
      asset: SanityImageAssetReference | null;
      alt: string | null;
      caption: string | null;
      externalUrl: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
    bio?: string;
  }> | null;
  faqHeading: string | null;
  faq: Array<
    {
      _key: string;
    } & FaqItem
  > | null;
  hero: {
    _type: "imageWithAlt";
    asset: SanityImageAssetReference | null;
    alt: string | null;
    caption: string | null;
    externalUrl: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  gallery: Array<{
    _type: "imageWithAlt";
    asset: SanityImageAssetReference | null;
    alt: string | null;
    caption: string | null;
    externalUrl: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _type: "imageWithAlt";
      asset: SanityImageAssetReference | null;
      alt: string | null;
      caption: string | null;
      externalUrl: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
    noIndex: boolean | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: allPackageSetsQuery
// Query: *[_type == "packageSet" && defined(slug.current)]{    _id,    _type,    title,    "slug": slug.current,    property,    alwaysIncluded,    packages[]{      ...,      images[] {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot}    }  }
export type AllPackageSetsQueryResult = Array<{
  _id: string;
  _type: "packageSet";
  title: string | null;
  slug: string | null;
  property: "seminyak" | "ubud" | null;
  alwaysIncluded: Array<string> | null;
  packages: Array<{
    _key: string;
    _type: "packageItem";
    name?: string;
    images: Array<{
      _type: "imageWithAlt";
      asset: SanityImageAssetReference | null;
      alt: string | null;
      caption: string | null;
      externalUrl: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    }> | null;
    description?: string;
    meta?: Array<
      {
        _key: string;
      } & PackageMeta
    >;
    benefitsHeading?: string;
    benefits?: Array<string>;
    notes?: Array<string>;
    ctas?: Array<
      {
        _key: string;
      } & Link
    >;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: allTestimonialsQuery
// Query: *[_type == "testimonial"] | order(order asc){    _id,    _type,    quote,    author,    property,    order  }
export type AllTestimonialsQueryResult = Array<{
  _id: string;
  _type: "testimonial";
  quote: string | null;
  author: string | null;
  property: "seminyak" | "ubud" | null;
  order: number | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: legalPageByPathQuery
// Query: *[_type == "legalPage" && path == $path][0]{    _id,    _type,    title,    path,    intro,    sections,    updatedAt,    seo {  title,  description,  image {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot},  noIndex}  }
export type LegalPageByPathQueryResult = {
  _id: string;
  _type: "legalPage";
  title: string | null;
  path: "/privacy-policy" | "/terms-conditions" | null;
  intro: string | null;
  sections: Array<
    | {
        heading?: string;
        items?: Array<string>;
        _type: "legalList";
        _key: string;
      }
    | {
        heading?: string;
        text?: string;
        _type: "legalParagraph";
        _key: string;
      }
  > | null;
  updatedAt: string | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _type: "imageWithAlt";
      asset: SanityImageAssetReference | null;
      alt: string | null;
      caption: string | null;
      externalUrl: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
    noIndex: boolean | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: propertyBySlugQuery
// Query: *[_type == "property" && slug == $slug][0]{    _id,    _type,    slug,    label,    logo {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot},    navItems,    addressLines,    phones,    email,    maps,    facebook,    instagram,    instagramFeedUrl,    instagramApiUrl,    bookingHref,    bookingWidgetId,    offersHref,    blogPosts,    awardBadges[] {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot},    awardVariant  }
export type PropertyBySlugQueryResult = {
  _id: string;
  _type: "property";
  slug: "seminyak" | "ubud" | null;
  label: string | null;
  logo: {
    _type: "imageWithAlt";
    asset: SanityImageAssetReference | null;
    alt: string | null;
    caption: string | null;
    externalUrl: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  navItems: Array<{
    label?: string;
    href?: string;
    inScope?: boolean;
    children?: Array<{
      label?: string;
      href?: string;
      inScope?: boolean;
      external?: boolean;
      _type: "navChild";
      _key: string;
    }>;
    _type: "navItem";
    _key: string;
  }> | null;
  addressLines: Array<string> | null;
  phones: Array<string> | null;
  email: string | null;
  maps: string | null;
  facebook: string | null;
  instagram: string | null;
  instagramFeedUrl: string | null;
  instagramApiUrl: string | null;
  bookingHref: string | null;
  bookingWidgetId: string | null;
  offersHref: string | null;
  blogPosts: Array<{
    title?: string;
    href?: string;
    _type: "blogTeaser";
    _key: string;
  }> | null;
  awardBadges: Array<{
    _type: "imageWithAlt";
    asset: SanityImageAssetReference | null;
    alt: string | null;
    caption: string | null;
    externalUrl: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  awardVariant: "grid" | "marquee" | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0]{    _id,    _type,    title,    description,    favicon {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot},    bookNowLabel,    footerNote,    legalLinks,    defaultSeo {  title,  description,  image {  _type,  asset,  alt,  caption,  externalUrl,  crop,  hotspot},  noIndex}  }
export type SiteSettingsQueryResult = {
  _id: string;
  _type: "siteSettings";
  title: string | null;
  description: string | null;
  favicon: {
    _type: "imageWithAlt";
    asset: SanityImageAssetReference | null;
    alt: string | null;
    caption: string | null;
    externalUrl: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  bookNowLabel: string | null;
  footerNote: string | null;
  legalLinks: Array<
    {
      _key: string;
    } & Link
  > | null;
  defaultSeo: {
    title: string | null;
    description: string | null;
    image: {
      _type: "imageWithAlt";
      asset: SanityImageAssetReference | null;
      alt: string | null;
      caption: string | null;
      externalUrl: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
    noIndex: boolean | null;
  } | null;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "page" && path == $path][0]{\n    _id,\n    _type,\n    title,\n    path,\n    property,\n    seo {\n  title,\n  description,\n  image {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n},\n  noIndex\n},\n    sections[] {\n  ...,\n  image {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n},\n  images[] {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n},\n  badges[] {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n},\n  items[]{\n    ...,\n    image {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n}\n  },\n  packages[]{\n    ...,\n    images[] {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n}\n  },\n  categories[]{\n    ...,\n    image {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n}\n  },\n  packageSet->{\n    _id,\n    title,\n    alwaysIncluded,\n    packages[]{\n      ...,\n      images[] {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n}\n    }\n  }\n}\n  }\n': PageByPathQueryResult;
    '\n  *[_type == "page" && defined(path)].path\n': AllPagePathsQueryResult;
    '\n  *[_type == "post" && path == $path][0] {\n  _id,\n  _type,\n  title,\n  path,\n  property,\n  date,\n  order,\n  excerpt,\n  image {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n},\n  "categories": categories[]->{_id, title, "slug": slug.current},\n  blocks[] {\n  ...,\n  _type == "articleImage" => {\n    image {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n}\n  },\n  _type == "articlePoints" => {\n    items[]{\n      ...,\n      body[]{\n        ...,\n        image {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n}\n      }\n    }\n  }\n},\n  seo {\n  title,\n  description,\n  image {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n},\n  noIndex\n}\n}\n': PostByPathQueryResult;
    '\n  *[_type == "post" && defined(path)] | order(date desc, order asc) {\n  _id,\n  _type,\n  title,\n  path,\n  property,\n  date,\n  order,\n  excerpt,\n  image {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n},\n  "categories": categories[]->{_id, title, "slug": slug.current},\n  blocks[] {\n  ...,\n  _type == "articleImage" => {\n    image {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n}\n  },\n  _type == "articlePoints" => {\n    items[]{\n      ...,\n      body[]{\n        ...,\n        image {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n}\n      }\n    }\n  }\n},\n  seo {\n  title,\n  description,\n  image {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n},\n  noIndex\n}\n}\n': AllPostsQueryResult;
    '\n  *[_type == "post" && property == $property && defined(path)] | order(date desc, order asc) {\n  _id,\n  _type,\n  title,\n  path,\n  property,\n  date,\n  order,\n  excerpt,\n  image {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n},\n  "categories": categories[]->{_id, title, "slug": slug.current},\n  blocks[] {\n  ...,\n  _type == "articleImage" => {\n    image {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n}\n  },\n  _type == "articlePoints" => {\n    items[]{\n      ...,\n      body[]{\n        ...,\n        image {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n}\n      }\n    }\n  }\n},\n  seo {\n  title,\n  description,\n  image {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n},\n  noIndex\n}\n}\n': PostsByPropertyQueryResult;
    '\n  *[_type == "post" && defined(path)].path\n': AllPostPathsQueryResult;
    '\n  *[_type == "room" && defined(slug.current)] | order(property asc, order asc, title asc) {\n  _id,\n  _type,\n  title,\n  "slug": slug.current,\n  property,\n  description,\n  details,\n  amenities,\n  facilities,\n  hero {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n},\n  gallery[] {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n},\n  order,\n  seo {\n  title,\n  description,\n  image {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n},\n  noIndex\n}\n}\n': AllRoomsQueryResult;
    '\n  *[_type == "room" && property == $property && defined(slug.current)] | order(order asc, title asc) {\n  _id,\n  _type,\n  title,\n  "slug": slug.current,\n  property,\n  description,\n  details,\n  amenities,\n  facilities,\n  hero {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n},\n  gallery[] {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n},\n  order,\n  seo {\n  title,\n  description,\n  image {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n},\n  noIndex\n}\n}\n': RoomsByPropertyQueryResult;
    '\n  *[_type == "experience" && defined(slug)] | order(group asc, title asc) {\n  _id,\n  _type,\n  title,\n  slug,\n  group,\n  eyebrow,\n  paragraphs,\n  recommendedFor,\n  note,\n  sections[]{\n    ...,\n    image {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n}\n  },\n  blocks,\n  programsHeading,\n  programs,\n  inclusions,\n  price,\n  highlightsHeading,\n  highlights[]{\n    ...,\n    icon {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n}\n  },\n  closingCta,\n  teamHeading,\n  team[]{\n    ...,\n    photo {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n}\n  },\n  faqHeading,\n  faq,\n  hero {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n},\n  gallery[] {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n},\n  seo {\n  title,\n  description,\n  image {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n},\n  noIndex\n}\n}\n': AllExperiencesQueryResult;
    '\n  *[_type == "experience" && slug == $slug][0] {\n  _id,\n  _type,\n  title,\n  slug,\n  group,\n  eyebrow,\n  paragraphs,\n  recommendedFor,\n  note,\n  sections[]{\n    ...,\n    image {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n}\n  },\n  blocks,\n  programsHeading,\n  programs,\n  inclusions,\n  price,\n  highlightsHeading,\n  highlights[]{\n    ...,\n    icon {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n}\n  },\n  closingCta,\n  teamHeading,\n  team[]{\n    ...,\n    photo {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n}\n  },\n  faqHeading,\n  faq,\n  hero {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n},\n  gallery[] {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n},\n  seo {\n  title,\n  description,\n  image {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n},\n  noIndex\n}\n}\n': ExperienceBySlugQueryResult;
    '\n  *[_type == "packageSet" && defined(slug.current)]{\n    _id,\n    _type,\n    title,\n    "slug": slug.current,\n    property,\n    alwaysIncluded,\n    packages[]{\n      ...,\n      images[] {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n}\n    }\n  }\n': AllPackageSetsQueryResult;
    '\n  *[_type == "testimonial"] | order(order asc){\n    _id,\n    _type,\n    quote,\n    author,\n    property,\n    order\n  }\n': AllTestimonialsQueryResult;
    '\n  *[_type == "legalPage" && path == $path][0]{\n    _id,\n    _type,\n    title,\n    path,\n    intro,\n    sections,\n    updatedAt,\n    seo {\n  title,\n  description,\n  image {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n},\n  noIndex\n}\n  }\n': LegalPageByPathQueryResult;
    '\n  *[_type == "property" && slug == $slug][0]{\n    _id,\n    _type,\n    slug,\n    label,\n    logo {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n},\n    navItems,\n    addressLines,\n    phones,\n    email,\n    maps,\n    facebook,\n    instagram,\n    instagramFeedUrl,\n    instagramApiUrl,\n    bookingHref,\n    bookingWidgetId,\n    offersHref,\n    blogPosts,\n    awardBadges[] {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n},\n    awardVariant\n  }\n': PropertyBySlugQueryResult;
    '\n  *[_type == "siteSettings"][0]{\n    _id,\n    _type,\n    title,\n    description,\n    favicon {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n},\n    bookNowLabel,\n    footerNote,\n    legalLinks,\n    defaultSeo {\n  title,\n  description,\n  image {\n  _type,\n  asset,\n  alt,\n  caption,\n  externalUrl,\n  crop,\n  hotspot\n},\n  noIndex\n}\n  }\n': SiteSettingsQueryResult;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
